### ISSUE TITLE
Dashboard for Jobs would be pretty cool.

### ISSUE THREAD

**Issue by colstrom** [JScott/robot_sweatshop#16]
Some sort of overview of Job History, maybe pass/fail states, build times, etc?

**Comment by JScott** [comment]
It might be but where would the data be stored? Is there a case for doubling back on the design decision to not store extraneous data instead of just publishing the it to subscribed services?

**Comment by JScott** [comment]
Related conversation to make my case:

```
2:14 PM <alisdair> yeah. i am pushing for stateless jenkins
2:14 PM <alisdair> if you want anything to survive past the execution of your job you better explicitly put it in an external system
2:15 PM <jevs> Yes! Right?!
2:15 PM <alisdair> then you can just build a jenkins server whenever you need it, whereever you need it
2:15 PM <inhumantsar> that’s my goal at the moment
2:15 PM <jevs> I’m sure you know how to store your data better than I do. Don’t rely on CI to be your database
2:16 PM <inhumantsar> gah ^^ this ^^
```

Not that I couldn't or it might not be helpful but it seems like the wrong, even potentially harmful, design.

**Comment by colstrom** [comment]
Agreed. This is an anti-feature for Robot Sweatshop. A dashboard service should probably tap the logs or event stream to populate its own persistent storage. I un-request this feature.
