### ISSUE TITLE
Deployment key not recognized from key-chain

### ISSUE THREAD

**Issue by kkwoker** [JScott/robot_sweatshop#19]
sweatshop keeps encountering exit status 128 (pubkey denied) when cloning a private repo. I switched into the ci-bot user and ran the git clone command and it clones it via ssh properly. Deployment keys are in the key-chain (ssh-add -L). 

Does robot_sweatshop look in the key-chain?

**Comment by JScott** [comment]
Which user is running the Robot Sweatshop process? Was the SSH agent set up before the worker was loaded by that user?

Robot Sweatshop relies on plain old UNIX protocol for this stuff. It doesn't do anything special with keys but the underlying system should give it access. It works exactly the same as when any user on your system logs on and has their SSH keys loaded.

**Comment by JScott** [comment]
I need more information to work on this. I have to assume the advice I gave resolved it.

**Comment by kkwoker** [comment]
Sorry justin! Was just side tracked with other stuff

**Comment by JScott** [comment]
Not a problem, I'm not exactly flush with time either :) I'm just clearing it off the issue list until there's more to work with
